"translation-unit\n"
"  declaration-seq\n"
"    declaration\n"
"      template-declaration\n"
"        token: Identifier: ( 1: 1) template\n"
"        token: Operator: ( 1: 9) <\n"
"        template-parameter-list\n"
"          template-parameter\n"
"            type-parameter\n"
"              token: Identifier: ( 1:10) typename\n"
"              token: Identifier: ( 1:19) T\n"
"        token: Operator: ( 1:20) >\n"
"        declaration\n"
"          block-declaration\n"
"            simple-declaration\n"
"              decl-specifier-seq\n"
"                decl-specifier\n"
"                  type-specifier\n"
"                    class-specifier\n"
"                      class-head\n"
"                        class-key\n"
"                          token: Identifier: ( 1:22) struct\n"
"                        class-head-name\n"
"                          token: Identifier: ( 1:29) foo\n"
"                      token: Operator: ( 2: 1) {\n"
"                      member-specification\n"
"                        access-specifier\n"
"                          token: Identifier: ( 3: 5) private\n"
"                        token: Operator: ( 3:12) :\n"
"                        member-declaration\n"
"                          decl-specifier-seq\n"
"                            decl-specifier\n"
"                              type-specifier\n"
"                                trailing-type-specifier\n"
"                                  simple-type-specifier\n"
"                                    type-name\n"
"                                      typedef-name\n"
"                                        token: Identifier: ( 4: 9) T\n"
"                          member-declarator-list\n"
"                            member-declarator\n"
"                              declarator\n"
"                                ptr-declarator\n"
"                                  noptr-declarator\n"
"                                    declarator-id\n"
"                                      id-expression\n"
"                                        unqualified-id\n"
"                                          token: Identifier: ( 4:11) bar\n"
"                          token: Operator: ( 4:14) ;\n"
"                      token: Operator: ( 5: 1) }\n"
"              token: Operator: ( 5: 2) ;\n"
"    declaration\n"
"      block-declaration\n"
"        simple-declaration\n"
"          decl-specifier-seq\n"
"            decl-specifier\n"
"              type-specifier\n"
"                trailing-type-specifier\n"
"                  simple-type-specifier\n"
"                    type-name\n"
"                      simple-template-id\n"
"                        template-name\n"
"                          token: Identifier: ( 6: 1) foo\n"
"                        token: Operator: ( 6: 4) <\n"
"                        template-argument-list\n"
"                          template-argument\n"
"                            type-id\n"
"                              type-specifier-seq\n"
"                                type-specifier\n"
"                                  trailing-type-specifier\n"
"                                    simple-type-specifier\n"
"                                      token: Identifier: ( 6: 5) int\n"
"                        token: Operator: ( 6: 8) >\n"
"          init-declarator-list\n"
"            init-declarator\n"
"              declarator\n"
"                ptr-declarator\n"
"                  noptr-declarator\n"
"                    declarator-id\n"
"                      id-expression\n"
"                        unqualified-id\n"
"                          token: Identifier: ( 6:10) baz\n"
"          token: Operator: ( 6:13) ;\n"
