"translation-unit\n"
"  declaration-seq\n"
"    declaration\n"
"      namespace-definition\n"
"        named-namespace-definition\n"
"          original-namespace-definition\n"
"            token: Identifier: ( 1: 1) namespace\n"
"            token: Identifier: ( 1:11) foo\n"
"            token: Operator: ( 2: 1) {\n"
"            namespace-body\n"
"              declaration-seq\n"
"                declaration\n"
"                  block-declaration\n"
"                    simple-declaration\n"
"                      decl-specifier-seq\n"
"                        decl-specifier\n"
"                          type-specifier\n"
"                            class-specifier\n"
"                              class-head\n"
"                                class-key\n"
"                                  token: Identifier: ( 3: 5) class\n"
"                                class-head-name\n"
"                                  class-name\n"
"                                    token: Identifier: ( 3:11) bar\n"
"                              token: Operator: ( 4: 5) {\n"
"                              member-specification\n"
"                                access-specifier\n"
"                                  token: Identifier: ( 5: 9) public\n"
"                                token: Operator: ( 5:15) :\n"
"                                member-declaration\n"
"                                  decl-specifier-seq\n"
"                                    decl-specifier\n"
"                                      type-specifier\n"
"                                        class-specifier\n"
"                                          class-head\n"
"                                            class-key\n"
"                                              token: Identifier: ( 6:13) class\n"
"                                            class-head-name\n"
"                                              class-name\n"
"                                                token: Identifier: ( 6:19) baz\n"
"                                          token: Operator: ( 7:13) {\n"
"                                          token: Operator: ( 8:13) }\n"
"                                  token: Operator: ( 8:14) ;\n"
"                              token: Operator: ( 9: 5) }\n"
"                      token: Operator: ( 9: 6) ;\n"
"            token: Operator: (10: 1) }\n"
"    declaration\n"
"      block-declaration\n"
"        simple-declaration\n"
"          decl-specifier-seq\n"
"            decl-specifier\n"
"              type-specifier\n"
"                trailing-type-specifier\n"
"                  simple-type-specifier\n"
"                    nested-name-specifier\n"
"                      namespace-name\n"
"                        original-namespace-name\n"
"                          token: Identifier: (12: 1) foo\n"
"                      token: Operator: (12: 4) ::\n"
"                      type-name\n"
"                        class-name\n"
"                          token: Identifier: (12: 6) bar\n"
"                      token: Operator: (12: 9) ::\n"
"                    type-name\n"
"                      class-name\n"
"                        token: Identifier: (12:11) baz\n"
"          init-declarator-list\n"
"            init-declarator\n"
"              declarator\n"
"                ptr-declarator\n"
"                  ptr-operator\n"
"                    token: Operator: (12:15) *\n"
"                  noptr-declarator\n"
"                    declarator-id\n"
"                      id-expression\n"
"                        unqualified-id\n"
"                          token: Identifier: (12:16) x\n"
"          token: Operator: (12:17) ;\n"
